portfolio: setup and mobile version skeleton
solog0039/Portfolio pull request #1
Opened 2022-04-27 21:58 UTC by solog0039

In this project
1. githu workflow created
2. CSS and HTML for toolbar and headline sections completed
3. tested

2022-04-27 22:34 UTC, ShahierNashaat requested changes
Hi @solog0039 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-27 22:34 UTC, ShahierNashaat commented on index.html
> +  <section class="toolbar">
- [ ] Please change this from `section` to header tag.

2022-04-27 22:34 UTC, ShahierNashaat commented on index.html
> +     <h1> Solomon</h1>
- [ ] Please change the `h1` tag to `a` tag as the logo must be in an `a` tag.

2022-04-27 22:34 UTC, ShahierNashaat commented on index.html
> +    </div>
- [ ] Please wrap the hamburger button inside a `nav` tag.

2022-04-27 22:34 UTC, ShahierNashaat commented on style.css
> +}
- [ ] Please make the `section` and the `header` responsive with the mobile size as they have to be in the Figma design suggestions you can remove display: absolute and make the width of the `header` and the `section` 100%.

your design 
![Screenshot from 2022-04-28 00-32-48](https://user-images.githubusercontent.com/33752735/165642259-33027608-a526-48aa-933c-cc6110b5e806.png)

Figma design
![Screenshot from 2022-04-27 20-47-24](https://user-images.githubusercontent.com/33752735/165642331-1d3789b6-9202-428a-9ea0-b53d3bb96664.png)

2022-04-28 14:21 UTC, solog0039 commented
changes requested by reviewer @ShahierNashaat  has been made. Project ready to ask for new review.

2022-04-28 17:05 UTC, Munsa1 requested changes
Hi @solog0039  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Good PR :heavy_check_mark: 
- Linters Passing :heavy_check_mark: 
- Readme file :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-28 17:05 UTC, Munsa1 commented on index.html
> +<!DOCTYPE html>
Great work implementing most of the requested changes.
- [ ] As stated by the previous reviewer, Kindly make your design responsive, you will need to do so in order to have a professional-looking portfolio. 
Your design 
![image](https://user-images.githubusercontent.com/81932478/165802874-0916ee06-2f62-458c-b8bc-cdc029833b72.png)

Figma Design
![image](https://user-images.githubusercontent.com/81932478/165803169-88326a71-9331-4bb2-9066-aa77c557705f.png)

- The issue is that as you develop your site you are not using the inspect tool to see how your site looks like in mobile view. [Check out this video](https://www.youtube.com/watch?v=x8ofsJiELQ0)
- Once you have opened your site in mobile view use CSS to style your portfolio to match the Figma template you chose.
- Width properties and height properties should be used with caution they make your site to be unresponsive. For example, if you give the `header` section width of 300px, this means when viewing your site on mobile as the screen gets bigger than 300px the header will become static and white space will remain to cause the issue that you're having right now. I would advise removing all width and height properties or making all of them 100% as the previous reviewer advised. [See this article](https://www.w3schools.com/html/html_responsive.asp)

2022-04-29 11:23 UTC, danielufeli approved these changes
Hi @solog0039,

Great work on making the changes requested by the previous reviewer 👏
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![a](https://camo.githubusercontent.com/40c24648ada128030359495b9504e95985194c3f4bbeabf0485e740ecd253bcc/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6a4a5143327075565a70544d4f34765573302f67697068792e676966)

## Highlights
- Nice commits messages✔️
- Descriptive PR ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @danielufeli in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-29 11:23 UTC, danielufeli commented on index.html
> +            <img  class="github" src="socialmedia/github.png" alt="github">
- [Optional] Kindly link each social icon using (`a` tag) for better user interaction.

2022-04-29 11:40 UTC, merged